sudo: false

language: node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_script:
  - adonis migration:run

# before_script:
#   - adonis serve --dev

script:
  - npm test
