sudo: false

language: node_js

node_js:
  - node

services:
  - sqlite3

# before_script:
#   - psql -c 'create database travis_ci_test;' -U postgres

before_script:
  - adonis migration:run

script:
  - npm test
